### PR TITLE
Multibyte string support by pre-splitted characters string

### PR DESCRIPTION
**Pull request by Thorn-workshop**
Make sure your TTF font supports the correct language.

### CODE REVIEW

**Comment by Thorn-workshop** [comment]
Hi!  why my commit was reverted? is any problems with it?

**Comment by mewebstudio** [comment]
Hi.
Only the same characters appear. Like 222222…
You can correct the error and send it again.

**Comment by Thorn-workshop** [comment]
strange. I did not have this error

**Comment by mewebstudio** [comment]
I tried your update and had this problem, sorry. Please try again.

**Comment by Thorn-workshop** [comment]
I updated and tested it. And already pushed it to my production (sample of work here http://cont.eurosib.biz/ru/contacts) pull request #161 is already waiting for your validation

**Comment by mewebstudio** [comment]
Merged, thank's.

**Pull request merged**
