### PR TITLE
[Bugfix] API Response: Resolved EncodedImage Error

### PR DESCRIPTION
**Pull request by mohaphez**
- **Fix:**
  - Resolved the error `Undefined property: Intervention\Image\EncodedImage::$encoded` by replacing `$this->image->encode()->encoded` with `$this->image->encode()->toDataUri()` in the codebase, ensuring proper handling of encoded images in API responses.

### CODE REVIEW

**Review by scarm01 — APPROVED** [review]

**Comment by scarm01** [comment]
Can we merge this, please?

**Comment by Kuasa5Indra** [comment]
@mohaphez please merge this as soon as possible. I also need that

**Comment by mohaphez** [comment]
Hi @Kuasa5Indra 

I don't have merge access , 
We waiting for @mewebstudio

**Comment by Kuasa5Indra** [comment]
> Hi @Kuasa5Indra
> 
> I don't have merge access , We waiting for @mewebstudio

Oh allright. Thanks for letting me know @mohaphez. Have a nice day

**Pull request merged**
